apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: veilwarden-tokenreview
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: veilwarden-tokenreview
subjects:
- kind: ServiceAccount
  name: veilwarden
  namespace: veilwarden
