apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: veilwarden

resources:
- namespace.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- configmap.yaml
- daemonset.yaml

images:
- name: veilwarden
  newTag: v0.2.0
